language: minimal
os: linux
dist: focal

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

services:
  - docker
 
jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t test-image .
      - docker run --rm test-image
